# Generated by Django 6.0.5 on 2026-06-10 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_alter_donation_phone'),
        ('users', '0002_user_county_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('case_refs', models.JSONField(default=list, help_text='List of case reference codes submitted by this user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bookmarked_orgs', models.ManyToManyField(blank=True, related_name='bookmarked_by', to='organisations.organisation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
