# Generated by Django 6.0.5 on 2026-06-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emergencycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='county',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('survivor', 'Survivor'), ('counselor', 'Counselor'), ('org_staff', 'Organization Staff'), ('county_official', 'County Official'), ('admin', 'Administrator')], default='survivor', max_length=20),
        ),
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
    ]
