# Generated by Django 6.0.5 on 2026-06-29 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='calls_made',
            new_name='requests_this_month',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='call_limit',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='name',
        ),
        migrations.AddField(
            model_name='apikey',
            name='monthly_limit',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('researcher', 'Researcher'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('requests_count', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intelligence.apikey')),
            ],
        ),
    ]
