# Generated by Django 6.0.5 on 2026-06-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountyScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=50, unique=True)),
                ('reporting_rate', models.FloatField()),
                ('conviction_rate', models.FloatField()),
                ('org_density', models.FloatField()),
                ('avg_response_time_hours', models.FloatField()),
                ('shelter_capacity_ratio', models.FloatField()),
                ('overall_score', models.FloatField()),
                ('rank', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScorecardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=50)),
                ('scorecard_data', models.JSONField()),
                ('snapshot_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
