# Generated by Django 6.0.5 on 2026-06-14 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('workshop_type', models.CharField(choices=[('financial_literacy', 'Financial Literacy'), ('legal_rights', 'Legal Rights'), ('self_defense', 'Self Defense'), ('trauma_healing', 'Trauma Healing'), ('digital_safety', 'Digital Safety')], max_length=50)),
                ('is_live', models.BooleanField(default=False)),
                ('meeting_url', models.URLField(blank=True)),
                ('recording_url', models.URLField(blank=True)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_rating', models.IntegerField(null=True)),
                ('feedback_text', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshops.workshop')),
            ],
        ),
        migrations.AddField(
            model_name='workshop',
            name='attendees',
            field=models.ManyToManyField(through='workshops.WorkshopAttendance', to=settings.AUTH_USER_MODEL),
        ),
    ]
