# Generated by Django 6.0.5 on 2026-06-14 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerSupporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_trained', models.BooleanField(default=False)),
                ('training_certified_date', models.DateField(null=True)),
                ('languages', models.JSONField(default=list)),
                ('counties', models.JSONField(default=list)),
                ('max_active_sessions', models.IntegerField(default=3)),
                ('current_sessions', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PeerSupportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonymous', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('escalated', 'Escalated')], max_length=20)),
                ('messages_json', models.JSONField(default=list)),
                ('supporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peer_support.peersupporter')),
                ('survivor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
