# Generated by Django 6.0.5 on 2026-07-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KenyanLawReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_name', models.CharField(max_length=200)),
                ('section', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('keywords', models.JSONField(default=list)),
                ('full_text_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LegalQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('law_citations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
