# Generated by Django 6.0.5 on 2026-06-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_text', models.TextField()),
                ('incident_county', models.CharField(max_length=50)),
                ('incident_date', models.DateTimeField()),
                ('reporter_relationship', models.CharField(choices=[('neighbor', 'Neighbor'), ('colleague', 'Colleague'), ('family', 'Family Member'), ('professional', 'Professional'), ('anonymous', 'Anonymous')], max_length=50)),
                ('is_urgent', models.BooleanField(default=False)),
                ('referred_to_org', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
            ],
        ),
    ]
