# Generated by Django 6.0.5 on 2026-06-29 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('abuse_type', models.CharField(choices=[('physical', 'Physical Abuse'), ('sexual', 'Sexual Abuse'), ('emotional', 'Emotional Abuse'), ('economic', 'Economic Abuse'), ('digital', 'Digital Abuse'), ('other', 'Other')], max_length=20)),
                ('relationship', models.CharField(choices=[('self', 'Self'), ('family', 'Family Member'), ('partner', 'Partner/Spouse'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('other', 'Other')], max_length=20)),
                ('county', models.CharField(max_length=50)),
                ('sub_county', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('abuse_type', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('sub_county', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
