# Generated by Django 6.0.5 on 2026-05-27 07:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('abuse_type', models.CharField(choices=[('physical', 'Physical'), ('emotional', 'Emotional'), ('financial', 'Financial'), ('sexual', 'Sexual'), ('digital', 'Digital')], max_length=20)),
                ('relationship', models.CharField(choices=[('self', 'Myself'), ('family', 'Family Member'), ('neighbour', 'Neighbour'), ('colleague', 'Colleague'), ('other', 'Other')], max_length=20)),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('evidence_url', models.URLField(blank=True)),
                ('sms_ref_code', models.CharField(blank=True, max_length=12)),
                ('urgency_score', models.IntegerField(blank=True, null=True)),
                ('ai_classification', models.CharField(blank=True, max_length=50)),
                ('flagged_for_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
