# Generated by Django 6.0.5 on 2026-06-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(max_length=12)),
                ('update_type', models.CharField(choices=[('follow_up', 'Follow Up'), ('police', 'Reported to Police'), ('legal', 'Legal Aid Contacted'), ('medical', 'Medical Attention Received'), ('shelter', 'Safe Shelter Found'), ('resolved', 'Case Resolved'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
