# Generated by Django 6.0.5 on 2026-07-07 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_add_uuid_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='uuid_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='uuid_id',
        ),
    ]
