# Generated by Django 6.0.5 on 2026-06-16 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_voicereport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abuse_type', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('sub_county', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CaseUpdate',
        ),
        migrations.DeleteModel(
            name='VoiceReport',
        ),
        migrations.AlterModelOptions(
            name='incidentreport',
            options={},
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='ai_classification',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='evidence_url',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='flagged_for_review',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='sms_ref_code',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='urgency_score',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='is_anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='abuse_type',
            field=models.CharField(choices=[('physical', 'Physical Abuse'), ('sexual', 'Sexual Abuse'), ('emotional', 'Emotional Abuse'), ('economic', 'Economic Abuse'), ('digital', 'Digital Abuse'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='county',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='relationship',
            field=models.CharField(choices=[('self', 'Self'), ('family', 'Family Member'), ('partner', 'Partner/Spouse'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='sub_county',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
