# Generated by Django 6.0.5 on 2026-06-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('county_official', 'County Official'), ('org_staff', 'Organisation Staff'), ('survivor', 'Registered Survivor'), ('public', 'Public')], default='public', max_length=20),
        ),
    ]
