# Generated by Django 6.0.5 on 2026-06-14 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('tier', models.CharField(choices=[('free', 'Free — 100 calls/month'), ('researcher', 'Researcher — 1,000 calls/month — KES 2,000'), ('enterprise', 'Enterprise — Unlimited — KES 10,000')], default='free', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('calls_made', models.IntegerField(default=0)),
                ('call_limit', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
