# Generated by Django 6.0.5 on 2026-07-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('org_type', models.CharField(choices=[('ngo', 'NGO'), ('cbo', 'Community Based Organization'), ('faith', 'Faith Based Organization'), ('government', 'Government Agency'), ('legal', 'Legal Aid'), ('shelter', 'Shelter'), ('health', 'Health Facility'), ('other', 'Other')], default='ngo', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('services', models.TextField(blank=True, help_text='Comma separated list of services')),
                ('county', models.CharField(max_length=50)),
                ('sub_county', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
