# Generated by Django 6.0.5 on 2026-06-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_organisationreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationreview',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='from_org',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='to_org',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='verified',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='document_url',
        ),
        migrations.AddField(
            model_name='organisation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='county',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='org_type',
            field=models.CharField(choices=[('ngo', 'NGO'), ('cbo', 'Community Based Organization'), ('faith', 'Faith Based Organization'), ('government', 'Government Agency'), ('legal', 'Legal Aid'), ('shelter', 'Shelter'), ('health', 'Health Facility'), ('other', 'Other')], default='ngo', max_length=20),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='services',
            field=models.TextField(blank=True, help_text='Comma separated list of services'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='sub_county',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='OrganisationReview',
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
