# Generated by Django 6.0.5 on 2026-07-07 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True)),
                ('format', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('guide', 'Downloadable Guide')], max_length=20)),
                ('topic', models.CharField(choices=[('recognise', 'Recognising Abuse'), ('legal', 'Legal Rights'), ('support', 'Supporting Survivors'), ('healthy', 'Healthy Relationships'), ('prevention', 'Prevention')], max_length=20)),
                ('youtube_url', models.URLField(blank=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('ai_review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='content.educationcontent')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('topic', models.CharField(choices=[('recognise', 'Recognising Abuse'), ('legal', 'Legal Rights'), ('support', 'Supporting Survivors'), ('healthy', 'Healthy Relationships'), ('prevention', 'Prevention')], max_length=20)),
                ('questions', models.JSONField(default=list)),
                ('approved', models.BooleanField(default=False)),
                ('completion_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='organisations.organisation')),
            ],
        ),
    ]
