# Generated by Django 6.0.5 on 2026-06-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('safety_plan', 'Safety Plan'), ('legal_handbook', 'Legal Handbook'), ('emergency_cards', 'Emergency Cards'), ('self_care', 'Self Care'), ('video', 'Video Tutorial'), ('guide', 'Guide')], max_length=20)),
                ('file_url', models.URLField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('is_downloadable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
