# Generated by Django 6.0.5 on 2026-06-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='org_type',
            field=models.CharField(choices=[('ngo', 'NGO'), ('county_govt', 'County Government'), ('legal_aid', 'Legal Aid Clinic'), ('health', 'Health Facility'), ('counselling', 'Counselling Centre'), ('other', 'Other')], default='ngo', max_length=20),
        ),
    ]
