# Generated by Django 6.0.5 on 2026-06-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organisation_org_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
