# Generated by Django 6.0.5 on 2026-06-14 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_alter_donation_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(max_length=12)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_sent', to='organisations.organisation')),
                ('to_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
